branches:
  only:
  - master
language: python
python:
  - "3.6.7"
install:
  - "pip install -r requirements.txt"
script:
    pytest --black --cov=. --cov-report=term-missing
after_success:
- COVERALLS_REPO_TOKEN=hKniAjX5XkR4mCPGjScmBSs734YmZwta4 coveralls